accounts/urls.py
# accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

datastats/urls.py
from django.urls import path

from . import views

app_name = 'datastats'
urlpatterns = [
    path('', views.summary, name='summary'),
    path('<int:dataset_id>/', views.dataset, name='dataset'),
]

pelorus/urls.py
from django.contrib import admin
from django.urls import include, path

from accounts import views as accounts_views


urlpatterns = [
    path('datastats/', include('datastats.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

datastats/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Dataset(models.Model):
    file_name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    load_date = models.DateTimeField('date loaded')
    
    def __str__(self):
        return self.file_name
        
    def was_uploaded_recently(self):
        return self.load_date >= timezone.now() - datetime.timedelta(days=1)
    
class Column(models.Model):
    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE)
    column_name = models.CharField(max_length=200, verbose_name="Column Name")
    column_type = models.CharField(max_length=200, verbose_name="Column Type")
    num_blank = models.IntegerField(verbose_name="Number Blank Values")
    num_unique = models.IntegerField(verbose_name="Number Unique Values")
    variability = models.FloatField(verbose_name="Variability Index")
    num_count = models.IntegerField(verbose_name="Number of Values (Numeric)", default=None, null=True)
    num_max = models.FloatField(verbose_name="Max Value", default=None, blank=True, null=True)
    num_min = models.FloatField(verbose_name="Min Value", default=None, blank=True, null=True)
    num_mean = models.FloatField(verbose_name="Avg Value", default=None, blank=True, null=True)
    num_std = models.FloatField(verbose_name="Std Deviation", default=None, blank=True, null=True)
    pct_25 = models.FloatField(verbose_name="25th Percentile", default=None, blank=True, null=True)
    pct_50 = models.FloatField(verbose_name="50th Percentile", default=None, blank=True, null=True)
    pct_75 = models.FloatField(verbose_name="75th Percentile", default=None, blank=True, null=True)
    
    def __str__(self):
        return self.column_name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
# accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

datastats/views.py
import csv, io, datetime
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from django.contrib import messages

from django.contrib.auth.decorators import login_required

from .models import Dataset, Column

import lib.datastats as datastats
# Create your views here.
@login_required()
def summary(request):
    if request.method == 'POST':
        #DEBUG
        messages.info(request, 'in upload_csv')
        try:
            csv_file = request.FILES['csv_file']
            dfData = datastats.process_csv(csv_file)
            #DEBUG
            messages.info(request, 'after csv file try'+str(csv_file.name))
            
            #Drop the index so the Column Name field is populated
            dfData = dfData.reset_index()
            dfData = dfData.rename(columns={
                'Col_Name':'column_name',
                'Type':'column_type',
                'Num_Blank':'num_blank',
                'Num_Unique':'num_unique',
                'Variability':'variability',
                'count':'num_count',
                'mean':'num_mean',
                'std':'num_std',
                'min':'num_min',
                '25%':'pct_25',
                '50%':'pct_50',
                '75%':'pct_75',
                'max':'num_max'})
            
            #DEBUG
            messages.info(request, 'after data rename')
            
            #Get the description entered by th user in the form
            description = str(request.POST.get('file_description'))
            
            #DEBUG
            messages.info(request, 'set description ='+description)
            
            #Create the new dataset row in the database
            new_dataset = Dataset(file_name=str(csv_file), description=description, load_date=datetime.datetime.now())
            new_dataset.save()
            
            #Get the current dataset id as the foreign key to insert inot the Column table
            dataset_id = new_dataset.id
            #Include that dataset id as the dataset id field value for all rows
            dfData['dataset_id'] = dataset_id
            
            #DEBUG
            #dfData.to_csv('out.csv')
            #DEBUG
            messages.info(request, 'after save dataset')
            
            #Convert the df to a dict so it can be inserted into the database
            dictColumns = dfData.apply(lambda x : x.dropna().to_dict(),axis=1)
            #Loop through the dictionary and insert each row
            for item in dictColumns:
                col_to_add = Column(**item)
                col_to_add.save()
                
            #DEBUG
            messages.info(request, 'after save')
        except Exception as e:
            messages.error(request, "Unable to upload file. "+repr(e))
            
    latest_dataset_list = Dataset.objects.order_by('-load_date')[:5]
    context = {'latest_dataset_list':latest_dataset_list}
    return render(request, 'datastats/index.html', context)
    
def dataset(request, dataset_id):
    dataset = get_object_or_404(Dataset, pk=dataset_id)
    return render(request, 'datastats/dataset.html', {'dataset': dataset})

datastats/templates/datastats/dataset.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'datastats:summary' %}">Datasets</a></li>
  <li class="breadcrumb-item active">{{ dataset }}</li>
{% endblock %}

{% block content %}
	<table id=dsColumns class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
		<thead>
			<th scope="col">Column Name</th>
			<th scope="col">Column Type</th>
			<th scope="col">Number of Blank Values</th>
			<th scope="col">Number of Unique Values</th>
			<th scope="col">Variability Index</th>
			<th scope="col">Maximum Value</th>
			<th scope="col">Minimum Value</th>
			<th scope="col">Average Value</th>
			<th scope="col">Standard Deviation</th>
		</thead>
		<tbody>
			{% for column in dataset.column_set.all %}
				<tr>
					<td><a href="/datastats/{{ column.id }}/">{{ column.column_name }}</a></td>
					<td>{{ column.column_type }}</td>
					<td>{{ column.num_blank }}</td>
					<td>{{ column.num_unique }}</td>
					<td>{{ column.variability }}</td>
					<td>{{ column.num_max }}</td>
					<td>{{ column.num_min }}</td>
					<td>{{ column.num_mean }}</td>
					<td>{{ column.num_std }}</td>
				</tr>
			{% endfor %}
		</tbody>
    </table>
{% endblock %}

{% block script %}
	<script>
		$(document).ready(function () {
			$('#dsColumns').DataTable();
			$('.dataTables_length').addClass('bs-select');
		});
	</script>
{% endblock %}

datastats/templates/datastats/index.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'datastats:summary' %}" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	<!-- <div class="input-group">
	  <div class="input-group-prepend">
		<span class="input-group-text" id="inputGroupFileAddon01">Upload New Dataset</span>
	  </div>
	  <div class="custom-file">
		<input type="file" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
		<label class="custom-file-label" for="inputGroupFile01">Choose file</label>
	  </div>
	</div> -->
	<div class="form-group">
		<label>Upload New Data File</label>
		<div>
			<input type="file" name="csv_file" size="50" required="True">
			<input type="text" name="file_description" size="75" placeholder="Description" required="True>
		</div		
	</div>
	<div>          
		<div style="margin-bottom:10px;">
			<button class="btn btn-primary mb-2"> <span style="margin-right:5px;"></span>Upload</button>
		</div> 
	</div>
</form>

<div class="card mt-4">
<h5 class="card-title ml-1">Datasets</h5>
{% if latest_dataset_list %}
    <table class="table">
		<thead>
			<th scope="col">Dataset Name</th>
			<th scope="col">Description</th>
			<th scope="col">Load Date</th>
		</thead>
		<tbody>
			{% for dataset in latest_dataset_list %}
				<tr>
					<td><a href="{% url 'datastats:dataset' dataset.id %}">{{ dataset.file_name }}</a></td>
					<td>{{ dataset.description }}</td>
					<td>{{ dataset.load_date }}</td>
				</tr>
			{% endfor %}
		</tbody>
    </table>
{% else %}
    <p>No datasets are available.</p>
{% endif %}
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Datastats{% endblock %}</title>
	<link href="https://fonts.googleapis.com/css?family=Antic" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/app.css' %}">
	<link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">
	{% block stylesheet %}{% endblock %}
  </head>
  <body>
    {% block body %}
		<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
			<div class="container">
				<a class="navbar-brand" href="{% url 'datastats:summary' %}">Pelorus</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="mainMenu">
					{% if user.is_authenticated %}
						<ul class="navbar-nav ml-auto">
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									{{ user.username }}
								</a>
								<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
									<a class="dropdown-item" href="#">My account</a>
									<a class="dropdown-item" href="#">Change password</a>
									<div class="dropdown-divider"></div>
									<a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
								</div>
							</li>
						</ul>
					{% else %}
						<form class="form-inline ml-auto">
							<a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
							<a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
						</form>
					{% endif %}
				</div>
			</div>
		</nav>
		
		{% if messages %}
			<ul class="messages">
				{% for message in messages %}
					<li>{{ message }}</li>
				{% endfor %}
<			</ul>
		{% endif %}

		<div class="container">
			<ol class="breadcrumb my-4">
			  {% block breadcrumb %}
			  {% endblock %}
			</ol>
			{% block content %}
			{% endblock %}
		</div>
	{% endblock body %}
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/datatables.min.js' %}"></script>	
	<script src="https://kit.fontawesome.com/c0cd745c9e.js" crossorigin="anonymous"></script>
	{% block script %}
	{% endblock %}
  </body>
</html>

templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'datastats:summary' %}">Pelorus</a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

templates/csv_upload.html
<form action="{% url "myapp:upload_csv" %}" method="POST" enctype="multipart/form-data" class="form-horizontal"> 
	{% csrf_token %}
	<div class="form-group">
		<label for="name" >File: </label>
		<div>
			<input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
		</div>                    
	</div>
	<div class="form-group">                    
		<div>
			<button> <span></span>Upload </button>
		</div> 
	</div>
</form>

templates/includes/form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text }}
      </small>
    {% endif %}
  </div>
{% endfor %}

templates/signup.html
{% extends 'base_accounts.html' %}

{% block title %}Sign up to Pelorus{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Sign up</h3>
          <form method="post" novalidate>
            {% csrf_token %}
			<input type="hidden" name="next" value="{{ next }}">
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Create an account</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          Already have an account? <a href="{% url 'login' %}">Log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}